apiVersion: v1
kind: Service
metadata:
  name: chk-gsheet-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8002
      protocol: TCP
  selector:
    app: chk-gsheet

